services:
#  bot:
#    container_name: "bot"
#    build: ./
#    command: sh -c "python main.py"
#    env_file:
#      - .env
#    depends_on:
#      - postgresdb

  nginx:
    container_name: "nginx"
    build: ./nginx
    restart: on-failure
    depends_on:
      - api
    ports:
      - 80:80

  api:
    container_name: "api"
    build: ./server
    depends_on:
      - postgresdb
    ports:
      - 8000:8000
    volumes:
      - ./logs:/app/logs/

  postgresdb:
    image: postgres:13.1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432

volumes:
  postgres_data:
