services:
  bot:
    container_name: "bot"
    build:
      dockerfile: bot.Dockerfile
    command: sh -c "python main.py"
    env_file:
      - .env
    depends_on:
      - postgresdb
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

  nginx:
    container_name: "nginx"
    build: ./nginx
    restart: on-failure
    depends_on:
      - api
    ports:
      - 80:80
    networks:
      - app-network

  api:
    container_name: "api"
    build:
      dockerfile: server.Dockerfile
    env_file:
      - ./.env
    depends_on:
      - postgresdb
#    ports:
#      - 8000:8000
    volumes:
      - ./logs:/app/logs/
    networks:
      - app-network

  postgresdb:
    image: postgres:13.1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
#    ports:
#      - 5432:5432
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
